# Generated by Django 4.0.7 on 2022-08-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_selection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='code',
        ),
        migrations.AddField(
            model_name='section',
            name='code',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
