# Generated by Django 4.0.7 on 2022-08-16 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unit_selection', '0003_remove_course_dept_name_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='ostad',
        ),
        migrations.AddField(
            model_name='section',
            name='instructor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='unit_selection.instructor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instructor',
            name='dept_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='unit_selection.departemant'),
        ),
    ]
