# Generated by Django 4.0.7 on 2022-08-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_selection', '0004_remove_section_ostad_section_instructor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_slot',
            name='day',
            field=models.CharField(choices=[('شنبه', 'شنبه'), ('یکشنبه', 'یکشنبه'), ('دوشنبه', 'دوشنبه'), ('سشنبه', 'سشنبه'), ('چهارشنبه', 'چهارشنبه')], default='شنبه', max_length=10),
        ),
    ]
