# Generated by Django 4.0.7 on 2022-08-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_selection', '0007_remove_course_exam_day_course_exam_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='gender',
            field=models.CharField(choices=[('مختلط', 'مختلط'), ('مرد', 'مرد'), ('زن', 'زن')], default='مختلط', max_length=10),
        ),
    ]
