# Generated by Django 4.0.7 on 2022-08-16 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unit_selection', '0008_section_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='dept_name',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='unit_selection.departemant'),
        ),
    ]
