# Generated by Django 4.0.7 on 2022-08-16 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unit_selection', '0012_alter_course_dept_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='dept_name',
        ),
    ]
